trigger:
- master

pool:
  name: Default

stages:

- stage: Build
  displayName: Build Stage

  jobs:

  - job: MavenBuild

    steps:

    - checkout: self

    - script: |
        java --version
        mvn --version
      displayName: Check Java and Maven

    - script: |
        mvn clean install
      displayName: Maven Build

- stage: Deploy
  displayName: Deploy Stage

  dependsOn: Build

  jobs:

  - job: DeployJob

    steps:

    - script: |
        mkdir C:\JavaDeployment

        copy target\*.jar C:\JavaDeployment
      displayName: Deploy JAR